#Expyriment 0.10.0 (Python 3.7.9), .xpe-file, coding: UTF-8
#date: Wed Mar 24 2021 12:07:38
#sha1: 5fbf58
#modules: 
#display: size=(3840, 2160), window_mode=False, open_gl=2
#os: uname_result(system='Linux', node='is154920', release='5.8.0-45-generic', version='#51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
4036,stderr,received,'Traceback (most recent call last):'
4036,stderr,received,'  File "parity_feedback.py", line 33, in <module>'
4036,stderr,received,'    Press the space bar to start.""")'
4036,stderr,received,"NameError: name 'TARGETS' is not defined"
